# Generated by Django 4.1.3 on 2023-08-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
